---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: icproxy
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: icproxy-view
subjects:
- kind: ServiceAccount
  name: icproxy
roleRef:
  kind: Role
  name: view
---
